# Generated by Django 5.1.5 on 2025-03-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('primary_ability', models.CharField(max_length=100)),
                ('hit_die', models.CharField(max_length=10)),
                ('saving_throws', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ability_scores', models.CharField(max_length=100)),
                ('traits', models.TextField()),
                ('age', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('additional_traits', models.TextField(blank=True)),
                ('additional_ability_scores', models.CharField(blank=True, max_length=100)),
                ('parent_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='character_management.race')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('inventory', models.TextField(blank=True)),
                ('spells', models.TextField(blank=True)),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_management.characterclass')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_management.race')),
                ('subrace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_management.subrace')),
            ],
        ),
    ]
