# Generated by Django 5.1.5 on 2025-03-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_management', '0002_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_player_character',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_management.characterclass'),
        ),
    ]
