# Generated by Django 5.1.5 on 2025-03-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_management', '0003_character_is_player_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_management.characterclass'),
        ),
    ]
