# Generated by Django 5.1.4 on 2025-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0003_campaign_creator_campaign_join_code_campaignplayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_players',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of players allowed in this campaign'),
        ),
    ]
