# Generated by Django 5.1.5 on 2025-03-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0004_campaign_max_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncharacter',
            name='is_player_character',
        ),
    ]
