# Generated by Django 5.1.6 on 2025-03-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_characterclass_race_subrace_character'),
        ('game', '0002_delete_empty'),
    ]

    operations = [
    ]
