# Generated by Django 5.1.5 on 2025-03-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_character_charisma_and_more'),
        ('game', '0004_campaign_campaigncharacter_campaignsession'),
    ]

    operations = [
    ]
