# Generated by Django 5.1.7 on 2025-03-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_character_charisma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='subrace',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='parent_race',
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='SubRace',
        ),
    ]
