# Generated by Django 5.1.5 on 2025-03-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_management', '__first__'),
        ('game', '0005_merge_20250313_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='subrace',
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_management.character'),
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='parent_race',
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='SubRace',
        ),
    ]
