# Generated by Django 5.1.4 on 2025-03-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_character_character_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncharacter',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigncharacter',
            name='character',
        ),
        migrations.DeleteModel(
            name='CampaignSession',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignCharacter',
        ),
    ]
